version: '3.9'

services:
  # db:
  #   restart: always
  #   build:
  #     context: ./postgres-setup
  #     dockerfile: Dockerfile

  #   ports:
  #     - '5432:5432'

  #   environment:
  #     - POSTGRES_DB=uav
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin

  #   volumes:
  #     - ./dbdata:/var/lib/postgresql/data/
  #     # - ./scripts/:/docker-entrypoint-initdb.d/

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  #   environment:
  #     - POSTGRES_DB=uav
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin

  #   ports:
  #     - '3000:3000'

  #   volumes:
  #     - ./frontend:/code/fronted

  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    # environment:
    #   - POSTGRES_DB=uav
    #   - POSTGRES_USER=admin
    #   - POSTGRES_PASSWORD=admin

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/code/backend

    # depends_on:
    #   - db
